version: '3'
services:
  gateway:
    image: gateway-image:latest
    container_name: "gateway"
    depends_on:
      - postgres
      - db_pgadmin
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - REDIS_URL=redis_cache:6379
      - SERVICE_DISCOVERY_URL=service_discovery:5001
    networks:
      pad-net:

  service_discovery:
    image: service-discovery-image:latest
    container_name: "service_discovery"
    restart: unless-stopped
    depends_on:
      - gateway
    networks:
      pad-net:
             
  inventory_service:
    image: inventory-image:latest
    container_name: "inventory"
    restart: unless-stopped
    depends_on:
      - service_discovery
    environment:
      - SERVICE_DISCOVERY_URL=service_discovery:5001
      - MY_IP=inventory
      - DB_HOST=my_postgres
      - DB_RO_HOST=my_postgres
      - DB_NAME=inventory_pad_lab
      - DB_USER=cristi
      - DB_PASSWORD=p4ssw0rd
    networks:
      pad-net:
      
  catalog_service:
    image: catalog-image:latest
    container_name: "catalog"
    restart: unless-stopped
    depends_on:
      - service_discovery
    environment:
      - SERVICE_DISCOVERY_URL=service_discovery:5001
      - MY_IP=catalog
      - DB_HOST=my_postgres
      - DB_RO_HOST=my_postgres
      - DB_NAME=catalog_pad_lab
      - DB_USER=cristi
      - DB_PASSWORD=p4ssw0rd
    networks:
      pad-net:        

  inventory_service2:
    image: inventory-image:latest
    container_name: "inventory2"
    restart: unless-stopped
    depends_on:
      - service_discovery
    environment:
      - SERVICE_DISCOVERY_URL=service_discovery:5001
      - MY_IP=inventory2
      - DB_HOST=my_postgres
      - DB_RO_HOST=my_postgres
      - DB_NAME=inventory_pad_lab
      - DB_USER=cristi
      - DB_PASSWORD=p4ssw0rd
    networks:
      pad-net:
      
  catalog_service2:
    image: catalog-image:latest
    container_name: "catalog2"
    restart: unless-stopped
    depends_on:
      - service_discovery
    environment:
      - SERVICE_DISCOVERY_URL=service_discovery:5001
      - MY_IP=catalog2
      - DB_HOST=my_postgres
      - DB_RO_HOST=my_postgres
      - DB_NAME=catalog_pad_lab
      - DB_USER=cristi
      - DB_PASSWORD=p4ssw0rd
    networks:
      pad-net:        
        
        
  redis_db:
    image: redis:latest
    container_name: "redis_cache"
    restart: unless-stopped
    networks:
      pad-net:
        
  postgres:
    image: postgres:14-alpine
    container_name: my_postgres
    environment:
      - POSTGRES_USER=cristi
      - POSTGRES_PASSWORD=p4ssw0rd
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      pad-net:
        
  db_pgadmin:
    image: dpage/pgadmin4
    container_name: pad_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=cristi@boris.info
      - PGADMIN_DEFAULT_PASSWORD=p4ssw0rd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5481:80"
    networks:
      pad-net:

volumes:
  pg_data:   
  pgadmin_data:
networks:
  pad-net:

