{
 "title": "Requests Status Code",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad Requests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"400\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Found Requests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Server Error Requests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"500\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}